/**
 *	Author:	Evan Krimpenfort
 *
 *	Project: Assignment_3.c (will be turned in as a pdf)
 */

/*
 * 1. Assuming a correct program show_args which prints its command-line arguments to standard output, 
 *    one per line, give the output generated by the shell command line:
 *
 *    $ ./show_args one two three four
 *    one
 *    two
 *    three
 *    four
 *
 * 2. Start with the following environment:
 *
 *    $ stty kill '@'
 *    $ stty erase '#'
 *    $ stty lnext '\'
 *    $ sh
 *
 *    Explain the results of each of the commands in the following transcript:
 *
 *    $ date\@				
 *    date@: not found
 *    $ date
 *    Fri Sep 2 09:10:45 EDT 2005
 *    $ #date
 *    Fri Sep 2 09:10:45 EDT 2005
 *    $ \#date
 */
